export const QUESTION_TYPE_IDS = [
  "short_text",
  "long_text",
  "rich_text",
  "single_select",
  "multi_select",
  "dropdown",
  "multi_select_dropdown",
  "yes_no",
  "image_choice",
  "comparison_choice",
  "ranked_choice",
  "number",
  "slider",
  "stepper",
  "currency",
  "percentage",
  "likert",
  "nps",
  "star_rating",
  "emoji_scale",
  "semantic_differential",
  "matrix_rating",
  "date",
  "date_range",
  "time",
  "datetime",
  "email",
  "phone",
  "address",
  "name",
  "file_upload",
  "image_upload",
  "signature",
  "audio_video",
  "matrix_single",
  "matrix_multi",
  "ranking",
  "constant_sum",
  "table_input",
  "hidden",
  "consent_checkbox",
  "opt_in_toggle",
] as const

export type QuestionTypeId = (typeof QUESTION_TYPE_IDS)[number]

export type QuestionTypeMeta = {
  id: QuestionTypeId
  label: string
  category: string
  description: string
  hasOptions: boolean
  hasConfig: boolean
}

export const QUESTION_TYPE_CATALOG: QuestionTypeMeta[] = [
  {
    id: "short_text",
    label: "Short text",
    category: "Text-Based",
    description: "Name, one-word or short answers",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "long_text",
    label: "Long text",
    category: "Text-Based",
    description: "Open-ended paragraph explanations",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "rich_text",
    label: "Rich text",
    category: "Text-Based",
    description: "Formatted input with bold and links",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "single_select",
    label: "Single select",
    category: "Choice-Based",
    description: "Radio buttons — pick exactly one",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "multi_select",
    label: "Multi-select",
    category: "Choice-Based",
    description: "Checkboxes — pick one or more",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "dropdown",
    label: "Dropdown",
    category: "Choice-Based",
    description: "Single choice in a compact menu",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "multi_select_dropdown",
    label: "Multi-select dropdown",
    category: "Choice-Based",
    description: "Multiple choices in a compact list",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "yes_no",
    label: "Yes / No",
    category: "Choice-Based",
    description: "Binary single-select",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "image_choice",
    label: "Image choice",
    category: "Choice-Based",
    description: "Select by clicking an image",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "comparison_choice",
    label: "Comparison choice",
    category: "Choice-Based",
    description: "Compare options with an image and title each — pick, rank, allocate, or rate",
    hasOptions: true,
    hasConfig: true,
  },
  {
    id: "ranked_choice",
    label: "Card sort / ranked choice",
    category: "Choice-Based",
    description: "Drag options into ranked order",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "number",
    label: "Number input",
    category: "Numeric",
    description: "Free numeric entry",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "slider",
    label: "Slider",
    category: "Numeric",
    description: "Numeric value via drag",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "stepper",
    label: "Stepper / counter",
    category: "Numeric",
    description: "Increment and decrement buttons",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "currency",
    label: "Currency / amount",
    category: "Numeric",
    description: "Numeric with currency formatting",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "percentage",
    label: "Percentage",
    category: "Numeric",
    description: "Percent value input",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "likert",
    label: "Likert scale",
    category: "Rating & Scale",
    description: "Strongly disagree to strongly agree",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "nps",
    label: "NPS (0–10)",
    category: "Rating & Scale",
    description: "How likely to recommend",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "star_rating",
    label: "Star rating",
    category: "Rating & Scale",
    description: "1–5 stars",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "emoji_scale",
    label: "Emoji / mood scale",
    category: "Rating & Scale",
    description: "3–5 emoji sentiment options",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "semantic_differential",
    label: "Semantic differential",
    category: "Rating & Scale",
    description: "Scale between opposite adjectives",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "matrix_rating",
    label: "Matrix / grid rating",
    category: "Rating & Scale",
    description: "Multiple items on the same scale",
    hasOptions: true,
    hasConfig: true,
  },
  {
    id: "date",
    label: "Date picker",
    category: "Date & Time",
    description: "Single date",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "date_range",
    label: "Date range",
    category: "Date & Time",
    description: "Start and end date",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "time",
    label: "Time picker",
    category: "Date & Time",
    description: "Time of day",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "datetime",
    label: "Date + time",
    category: "Date & Time",
    description: "Combined date and time",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "email",
    label: "Email",
    category: "Contact & Identity",
    description: "Validated email format",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "phone",
    label: "Phone number",
    category: "Contact & Identity",
    description: "Optional country code",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "address",
    label: "Address",
    category: "Contact & Identity",
    description: "Street, city, zip, country",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "name",
    label: "Name",
    category: "Contact & Identity",
    description: "First and last name fields",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "file_upload",
    label: "File upload",
    category: "File & Media",
    description: "Document, PDF, etc.",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "image_upload",
    label: "Image upload",
    category: "File & Media",
    description: "Image file upload",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "signature",
    label: "Signature capture",
    category: "File & Media",
    description: "Drawn or typed signature",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "audio_video",
    label: "Audio / video recording",
    category: "File & Media",
    description: "Record directly in-browser",
    hasOptions: false,
    hasConfig: false,
  },
  {
    id: "matrix_single",
    label: "Matrix (single-select)",
    category: "Structured / Advanced",
    description: "One choice per row",
    hasOptions: true,
    hasConfig: true,
  },
  {
    id: "matrix_multi",
    label: "Matrix (multi-select)",
    category: "Structured / Advanced",
    description: "Multiple choices per row",
    hasOptions: true,
    hasConfig: true,
  },
  {
    id: "ranking",
    label: "Ranking",
    category: "Structured / Advanced",
    description: "Order items by preference",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "constant_sum",
    label: "Constant sum",
    category: "Structured / Advanced",
    description: "Distribute 100 points across options",
    hasOptions: true,
    hasConfig: true,
  },
  {
    id: "table_input",
    label: "Table / grid input",
    category: "Structured / Advanced",
    description: "Free-form rows and columns",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "hidden",
    label: "Hidden field",
    category: "Structured / Advanced",
    description: "Pre-filled via URL, not shown",
    hasOptions: false,
    hasConfig: true,
  },
  {
    id: "consent_checkbox",
    label: "Consent checkbox",
    category: "Consent & Legal",
    description: "I agree to terms",
    hasOptions: true,
    hasConfig: false,
  },
  {
    id: "opt_in_toggle",
    label: "Opt-in toggle",
    category: "Consent & Legal",
    description: "Marketing / GDPR-style consent",
    hasOptions: true,
    hasConfig: false,
  },
]

export const QUESTION_TYPE_MAP = Object.fromEntries(
  QUESTION_TYPE_CATALOG.map((item) => [item.id, item])
) as Record<QuestionTypeId, QuestionTypeMeta>

export function isQuestionTypeId(value: string): value is QuestionTypeId {
  return (QUESTION_TYPE_IDS as readonly string[]).includes(value)
}

export function questionTypesByCategory() {
  const groups = new Map<string, QuestionTypeMeta[]>()
  for (const type of QUESTION_TYPE_CATALOG) {
    const list = groups.get(type.category) ?? []
    list.push(type)
    groups.set(type.category, list)
  }
  return groups
}
